apiVersion: v1
kind: PersistentVolume
metadata:
  name: blackbeard
  namespace: blackbeard
spec:
  storageClassName: streaming-nfs
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.68.111
    path: "/"
    readOnly: false