apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n
  namespace: tools
data:
  N8N_SECURE_COOKIE: "false"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"
  NODE_FUNCTION_ALLOW_EXTERNAL: "@tryghost/admin-api"
  NODE_FUNCTION_ALLOW_BUILTIN: "*"
  N8N_EDITOR_BASE_URL: "https://n8n.appchemy.co.za"
  N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
  WEBHOOK_URL: "https://n8n.appchemy.co.za"