# metallb-addresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.68.10-192.168.68.14
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-adv
  namespace: metallb-system