apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: plane-r2-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: http://192.168.68.54:8080/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/Cloudflare/R2"
  managedKubeSecretReferences:
    - secretName: plane-r2
      secretNamespace: plane-ce
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          AWS_ACCESS_KEY_ID: "{{ .key.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .secret.Value }}"
          AWS_REGION: "auto"
          AWS_BUCKET: "plane"
          AWS_ENDPOINT: "https://{{ .host.Value }}"

---

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: plane-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: http://192.168.68.54:8080/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/Plane"
  managedKubeSecretReferences:
    - secretName: plane
      secretNamespace: plane-ce
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          DATABASE_URL: "{{ .pgdb_url.Value }}"
          REDIS_URL: "redis://plane-redis.plane-ce:6379"
          AMQP_URL: "amqp://plane:plane@plane-rabbitmq.plane-ce:5672"
          SECRET_KEY: " {{ .secret_key.Value }}"
