apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gitea-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: http://192.168.68.54:8080/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/Gitea"
  managedKubeSecretReferences:
    - secretName: gitea
      secretNamespace: tools
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
