apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-secrets
  namespace: infisical-operator-system
spec:
  hostAPI: http://192.168.68.54:8080/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/Cloudflare"
  managedKubeSecretReferences:
    - secretName: cloudflare-api-key-secret
      secretNamespace: cert-manager
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
    - secretName: cloudflare-token
      secretNamespace: dns
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
