apiVersion: v1
kind: PersistentVolume
metadata:
  name: communication
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.68.111
    path: /k0s-storage/communication
  persistentVolumeReclaimPolicy: Retain
  storageClassName: communication-nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: communication-pvc
  namespace: communication
spec:
  storageClassName: communication-nfs
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi