apiVersion: v1
kind: PersistentVolume
metadata:
  name: plane
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.68.111
    path: /k0s-storage/plane
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plane-nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plane-pvc
  namespace: plane-ce
spec:
  storageClassName: plane-nfs
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi