apiVersion: v1
kind: PersistentVolume
metadata:
  name: tools
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.68.111
    path: /k0s-storage/tools
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tools-nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools-pvc
  namespace: tools
spec:
  storageClassName: tools-nfs
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 30Gi