apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-redis
  namespace: plane-ce
  labels:
    app: plane-redis
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plane-redis
  template:
    metadata:
      labels:
        app: plane-redis
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --raw
            - incr
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --raw
            - incr
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - mountPath: '/data'
          name: storage-volume
          subPath: plane/redis/data
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: plane-pvc