apiVersion: v1
kind: Service
metadata:
  name: plane-redis
  namespace: plane-ce
spec:
  selector:
    app: plane-redis
  ports:
  - port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: plane-rabbitmq
  namespace: plane-ce
spec:
  selector:
    app: plane-rabbitmq
  ports:
  - port: 5672
    targetPort: 5672