apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nocodb-secrets
  namespace: infisical-operator-system
spec:
  # 1) Point to your external Infisical API:
  hostAPI: http://192.168.68.54:8080/api

  # 2) How often to re-sync (in seconds):
  resyncInterval: 10

  # 3) Authenticate via the service token you stored:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/Nocodb"

  # 4) Where to write them inside k8s:
  managedKubeSecretReferences:
    - secretName: nocodb
      secretNamespace: tools
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
